### ISSUE TITLE
Query Subpath after find()

### ISSUE THREAD

**Issue by markusressel** [eldomagan/axios-rest#5]
Hey there, 
is it possible to query urls like this:

```
http://localhost/document/4362010470902532462/content
```
where **4362010470902532462** is the ID of a specific document?

In code I would expect something like this (but of course this wont work currently):
```
let document = this.API.documents.find(documentId).content.all();
```

**Comment by eldomagan** [comment]
You can do that

```javascript
let document = this.API.documents[documentId].content.all()
```

**Comment by markusressel** [comment]
Ahh! It works :-)
Thx for the fast response and the great library!
